# General pipeline config
SLACK_CHANNEL_NAME: "#build-status"
ENVIRONMENT: prod
ACTION_MESSAGE: "Kubernetes Deployment completed!"
KEEP_APPROVAL_STAGE: true

# Ansible repo and playbook config
ANSIBLE_REPO: "https://github.com/nitinsingh4857/ansible-k8s-automation.git"
ANSIBLE:
  PLAYBOOK: deploy-k8s.yml
  INVENTORY: inventories/prod/hosts

